- hosts: local
  connection: local
  gather_facts: false
  vars:
    base_dir: "{{ lookup('env','base_dir') }}"
  tasks:
  - file: dest={{ base_dir }}/inventory/hosts state=absent
  - copy: src=files/hosts.default dest={{ base_dir }}/inventory/hosts
  - template: src=files/ec2.ini.j2 dest={{ base_dir }}/inventory/ec2.ini
