- hosts: riak
  connection: local
  any_errors_fatal: True
  tasks:
  - ec2_vol:
      region: "{{ region }}"
      instance: "{{ ec2_id }}"
      volume_size: "{{ vol_size }}"
      volume_type: "{{ vol_type }}"
      iops: "{{ vol_iops }}"
      device_name: "{{ vol_device }}"
    when: vol_iops != "none"
  - ec2_vol:
      region: "{{ region }}"
      instance: "{{ ec2_id }}"
      volume_size: "{{ vol_size }}"
      volume_type: "{{ vol_type }}"
      device_name: "{{ vol_device }}"
    when: vol_iops == "none"

- hosts: riak
  sudo: true
  tasks:
  - command: parted -s /dev/{{ vol_device }} mklabel msdos mkpart primary ext4 1MiB 100% creates=/dev/{{ vol_device }}1
  - filesystem: fstype=ext4 device=/dev/{{ vol_device }}1
  - mount: name={{ vol_mount }} src=/dev/{{ vol_device }}1 fstype=ext4 opts=noatime,data=writeback,barrier=0 state=mounted
