- hosts: master
  sudo: true
  any_errors_fatal: True
  vars:
    influxdb_pkg: influxdb_0.9.4.1_amd64.deb
  tasks:
  - command: wget https://s3.amazonaws.com/influxdb/{{ influxdb_pkg }} creates={{ influxdb_pkg }}
  - command: dpkg -i {{ influxdb_pkg }}
  - service: name=influxdb state=started
  - command: /opt/influxdb/influx -execute 'create database {{ influxdb_db }}'
    ignore_errors: yes

- hosts: riak
  sudo: true
  any_errors_fatal: True
  vars:
    telegraf_pkg: telegraf_0.1.8_amd64.deb
  tasks:
  - command: wget http://get.influxdb.org/telegraf/{{ telegraf_pkg }} creates={{ telegraf_pkg }}
  - command: dpkg -i {{ telegraf_pkg }}
  - template: src=files/riak-telegraf.toml dest=/etc/opt/telegraf/telegraf.conf
  - service: name=telegraf state=started

- hosts: bench
  sudo: true
  any_errors_fatal: True
  vars:
    telegraf_pkg: telegraf_0.1.8_amd64.deb
  tasks:
  - command: wget http://get.influxdb.org/telegraf/{{ telegraf_pkg }} creates={{ telegraf_pkg }}
  - command: dpkg -i {{ telegraf_pkg }}
  - template: src=files/bench-telegraf.toml dest=/etc/opt/telegraf/telegraf.conf
  - service: name=telegraf state=started
