- hosts: riak
  connection: local
  gather_facts: false
  tasks:
  - ec2_vol: state=list region={{ region }} instance={{ ec2_id }}
    register: vols

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Remove Riak Nodes
    local_action:
      module: ec2
      image: "{{ riak_ami }}"
      instance_type: "{{ riak_size }}"
      instance_tags:
        Type: Riak
      count_tag:
        Type: Riak
      wait: yes
      region: "{{ region }}"
      wait_timeout: 500
      exact_count: 0

- hosts: riak
  connection: local
  gather_facts: false
  tasks:
  - ec2_vol: id={{ item.id }} region={{ region }} state=absent
    with_items: vols.volumes
    when: item.attachment_set.device == vol_device

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Remove Bench Nodes
    local_action:
      module: ec2
      image: "{{ bench_ami }}"
      instance_type: "{{ bench_size }}"
      instance_tags:
        Type: Bench
      count_tag:
        Type: Bench
      wait: yes
      region: "{{ region }}"
      wait_timeout: 500
      exact_count: 0
