- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: ec2 group
    local_action:
      module: ec2_group
      name: "{{ set_name }}"
      description: "{{ set_name }}"
      region: "{{ region }}"
      vpc_id: "{{ vpcid }}"
      state: absent
  - ec2_vpc:
      resource_tags: { "Name":"{{ set_name }}", "Environment":"{{ aws_env }}" }
      state: absent
      vpc_id: "{{ vpcid }}"
      region: "{{ region }}"
      wait: yes
